### PR TITLE
Fix/remove open-session-in-view

### LINKED ISSUE #118: Fix open-session-in-view
Fix the open-session-in-view problem in both Spring & Quarkus versions by introducing a DTO layer and have mapping inside a transactional service layer.

### PR DESCRIPTION
**Pull request by edeandrea**
Fixes #118

### CODE REVIEW

File: quarkus3-spring-compatibility/src/main/java/org/acme/dto/AddressDTO.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+  public static Builder builder() {
+    return new Builder();
+  }
+
+  public Builder toBuilder() {
+    return new Builder(this);
+  }
+
+  public static class Builder {
```
Comment (franz1981) [inline quarkus3-spring-compatibility/src/main/java/org/acme/dto/AddressDTO.java]: It is that common that users allocate a builder too?
Since is a CPU bound scenario I would prefer not putting even more pressure to the GC if not required

**Review by franz1981 — CHANGES_REQUESTED** [review]

File: quarkus3-spring-compatibility/src/main/java/org/acme/dto/FruitDTO.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+  public Builder toBuilder() {
+    return new Builder(this);
+  }
+
+  public static class Builder {
+    private Long id;
+    private String name;
+    private String description;
+    private List<StoreFruitPriceDTO> storePrices = new ArrayList<>();
```
Comment (franz1981) [inline quarkus3-spring-compatibility/src/main/java/org/acme/dto/FruitDTO.java]: Ditto as before with the problem that in theory we know upfront the size of this list and we could just allocate a List.of (which is immutable and more optimized in term of allocation size) on the record

File: quarkus3-spring-compatibility/src/main/java/org/acme/dto/StoreFruitPriceDTO.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    return new Builder();
+  }
+
+  public Builder toBuilder() {
+    return new Builder(this);
+  }
+
+  public static class Builder {
+    private StoreDTO store;
+    private BigDecimal price;
```
Comment (franz1981) [inline quarkus3-spring-compatibility/src/main/java/org/acme/dto/StoreFruitPriceDTO.java]: We could just use a primitive float/double in the record as well saving allocating full blown costly objects

Comment (edeandrea) [reply quarkus3-spring-compatibility/src/main/java/org/acme/dto/StoreFruitPriceDTO.java]: We could, but should we? We'd potentially lose the precision (we're modeling prices in a local currency).
